[package]
name = "rust_web_thread_experiment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.5.1"
crossbeam-queue = "0.3.11"
rand = "0.8.5"